steps:
- name: node:12
  entrypoint: npm
  args: ["install"]
- name: node:12
  entrypoint: npm
  args: ["run", "build"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "dispatch.yaml"]
timeout: "1600s"